### ISSUE TITLE
Potential issue with draft revisions on live recipes

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#2040] opened 2019-11-01 23:02 UTC
At 6:08pm EDT I added a new revision to recipe 857. This revision is never approved but we see the spike in unenrollments that we were trying to fix is now fixed in the dashboard.

After writing that revision I went to go check on something else by copying the recipe from the v1 API into devtools and I'm not 100% sure but I think the filter expression had actually updated to include all the changes.

This would mean that draft revisions are being promoted to live as soon as they are created and before they are approved. We should definitely investigate this as this would be a major issue.

[edit by mythmon: [A living document with the timeline of events](https://docs.google.com/document/d/1wo95lEUuvsaKyD9iEPzAIGBkzWSR9UerPOogq3jn-sM/edit#)]

**Comment by tdsmith** [comment] 2019-11-01 23:31
The query showing unenrollments is https://sql.telemetry.mozilla.org/queries/65804#167113.

**Comment by mythmon** [comment] 2019-11-02 00:44
I did a test on both stage and prod. I published a recipe, and then made a draft change to it. The draft was not visible until approved, as it's supposed to.

I also verified the timeline of events. The unenrollment spike starts when revision 2785 was published, which was the change I made. The unenrollment spike ends when revision 2788 was *created*, not published. No change is observed when 2789 is created or published.

I see the same problem in the data, and I can't reproduce it. I don't have any theories at this time.

**Comment by leplatrem** [comment] 2019-11-05 19:11
The recipe 857 was created on 2019-10-30T22:16:21.150102 with the following data:
```
    {
      "uri": "/buckets/main-workspace/collections/normandy-recipes/records/857",
      "date": "2019-10-30T22:16:21.150102",
      "action": "create",
      "target": {
        "data": {
          "id": "857",
          "recipe": {
            "id": 857,
            "name": "DoH US Engagement Study V2",
            "action": "multi-preference-experiment",
            "arguments": {
              "slug": "pref-doh-us-engagement-study-v2-release-69-71-bug-1590831",
              "branches": [
                {
                  "slug": "disabled",
                  "ratio": 50,
                  "preferences": {
                    "doh-rollout.enabled": {
                      "preferenceType": "boolean",
                      "preferenceValue": false,
                      "preferenceBranchType": "default"
                    }
                  }
                },
                {
                  "slug": "enabled",
                  "ratio": 50,
                  "preferences": {
                    "doh-rollout.enabled": {
                      "preferenceType": "boolean",
                      "preferenceValue": true,
                      "preferenceBranchType": "default"
                    }
                  }
                }
              ],
              "userFacingName": "DNS over HTTPS US Rollout",
              "experimentDocumentUrl": "https://experimenter.services.mozilla.com/experiments/doh-us-engagement-study-v2/",
              "userFacingDescription": "This Firefox experiment will measure the impact on user engagement and retention when DNS over HTTPS is rolled out in the United States. Users who are part of the study will receive a notification before DNS over HTTPS is enabled. Set network.trr.mode to ‘5’ in about:config to permanently disable DoH. This experiment does not collect personally-identifiable information, DNS queries, or answers."
            },
            "revision_id": "2785",
            "capabilities": [
              "action.multi-preference-experiment",
              "jexl.transform.bucketSample"
            ],
            "filter_expression": "(normandy.locale in [\"en-GB\",\"en-CA\",\"en-US\"]) && (normandy.channel in [\"release\"]) && ((normandy.version>=\"69\"&&normandy.version<\"70\")||(normandy.version>=\"70\"&&normandy.version<\"71\")||(normandy.version>=\"71\"&&normandy.version<\"72\")) && ([\"doh-rollout\",normandy.userId]|bucketSample(0,100,10000)) && ((normandy.version >= \"70.\" || normandy.telemetry.main.application.buildId >= \"20191009172106\")\n&& (normandy.country == \"US\" || normandy.telemetry.main.environment.experiments[normandy.recipe.arguments.slug])\n&& normandy.addons[\"doh-rollout@mozilla.org\"].isActive\n&& normandy.addons[\"doh-rollout@mozilla.org\"].version >= \"1.0.4\"\n&& normandy.os.isWindows)"
          },
          "signature": {
            "x5u": "https://content-signature-2.cdn.mozilla.net/chains/normandy.content-signature.mozilla.org-2019-12-01-23-33-57.chain?cachebust=2017-06-13-21-06",
            "signature": "7p1atcEP9z_W32nagmYZSJgj97UNST8lQjuDy7Uni5DecWUCagqKyaTN5gQaQaqBHk6iJE5cPgd_hnadmn6ohfCINAssx31BSqtpcsmvNuOQYr_UfGPrwJ-5JWTER-Ew",
            "timestamp": "2019-10-30T22:16:20.313335Z",
            "public_key": ""
          },
          "last_modified": 1572473781138
        },
        "permissions": {
          "write": [
            "account:normandy_server"
          ]
        }
      },
      "user_id": "account:normandy_server",
      "record_id": "857",
      "collection_id": "normandy-recipes",
      "resource_name": "record",
      "id": "434aed88-ff6f-4fba-a7ba-9ae61618acec",
      "last_modified": 1572473781158
    }

```

It was then updated (revision 2787) on 2019-11-01T21:08:57.791746

And then again (revision 2789) on 2019-11-01T22:38:34.591187 

As far as I can tell, it's still published.

-----------------------------------------------

> Notes

I fetched the history of this recipe on Remote Settings, using this:

`curl 'https://settings-writer.prod.mozaws.net/v1/buckets/main-workspace/history?collection_id=normandy-recipes&resource_name=record&target.data.id="857"&_limit=10' -H 'Authorization: Bearer FV7i...'`

The bearer token can be obtained from the Admin UI (copy button in header).

**Comment by mythmon** [comment] 2019-11-06 21:44
I've compiled all the events from Normandy and Remote Settings into [this timeline](https://docs.google.com/document/d/1wo95lEUuvsaKyD9iEPzAIGBkzWSR9UerPOogq3jn-sM/edit). So far I don't see any evidence that the draft revision was published to remote settings erroneously.

**Comment by tdsmith** [comment] 2019-11-07 00:09
I was looking at the ages associated with settings-changes-monitoring events reported by uptake telemetry.

The median `age` of the `settings-changes-monitoring` events reported each minute, according to Firefox client clocks in UTC, has a sawtooth pattern; it increases linearly, interrupted by resets to small values [when new remote settings data is published](https://bugzilla.mozilla.org/show_bug.cgi?id=1523311). Because these are client clock values based on a timestamp with 1 minute precision, there's a little bit of smearing.

Here's the plot for November 1: https://sql.telemetry.mozilla.org/queries/65890#167278

There are minima indicating that new data were published at some critical times, including:
21:09 - revision 2787 was published
22:08 - revision 2788 was created (which should not have caused published data to change!)
22:39 - revision 2789 was published

What new settings were published at 22:08?

**Comment by leplatrem** [comment] 2019-11-07 00:30
Indeed, I can confirm that one change was published at 22:08:

```
    {
      "datetime": "2019-11-02T00:00:24.747260",
      "by": "account:normandy_server",
      "changes": 14
    },
    {
      "datetime": "2019-11-01T22:38:38.154693",
      "by": "account:normandy_server",
      "changes": 1
    },
    {
      "datetime": "2019-11-01T22:08:01.739147",
      "by": "account:normandy_server",
      "changes": 1
    },
    {
      "datetime": "2019-11-01T21:08:59.987229",
      "by": "account:normandy_server",
      "changes": 1
    },
    {
      "datetime": "2019-10-31T17:44:56.844841",
      "by": "account:normandy_server",
      "changes": 1
    },
```

And it's the recipe 863 that was created:

```
    {
      "uri": "/buckets/main-workspace/collections/normandy-recipes/records/863",
      "date": "2019-11-01T22:07:59.404466",
      "action": "create",
      "target": {
        "data": {
          "id": "863",
          "recipe": {
            "id": 863,
            "name": "Nov 2019 Monthly Favorites Survey (Bug 1592774)",
            "action": "show-heartbeat",
            "arguments": {
              "message": "Please help make Firefox better by taking this short survey",
              "surveyId": "hb-nov19-favorites-survey",
              "learnMoreUrl": "https://support.mozilla.org/kb/rate-your-firefox-experience-heartbeat",
              "repeatOption": "once",
              "postAnswerUrl": "https://qsurvey.mozilla.com/s3/favorites-survey",
              "thanksMessage": "Thanks",
              "learnMoreMessage": "Learn More",
              "includeTelemetryUUID": false,
              "engagementButtonLabel": "Take Survey"
            },
            "revision_id": "2786",
            "capabilities": [
              "action.show-heartbeat",
              "jexl.transform.bucketSample"
            ],
            "filter_expression": "(normandy.locale in [\"en-AU\",\"en-GB\",\"en-CA\",\"en-NZ\",\"en-ZA\",\"en-US\"]) && (normandy.country in [\"US\"]) && (normandy.channel in [\"release\"]) && ([\"global-v1\",normandy.userId]|bucketSample(6115,50,10000)) && (\"toolkit.telemetry.unified\"|preferenceValue == true)"
          },
          "signature": {
            "x5u": "https://content-signature-2.cdn.mozilla.net/chains/normandy.content-signature.mozilla.org-2019-12-01-23-33-57.chain?cachebust=2017-06-13-21-06",
            "signature": "KLGJnbZ7vNcx7T_IaEA8M4CKJ2v-32_TcbkdWlvc5NRG2n53HBzPyR8wXdMlgka-eZ-uISsm925jRzcus7db9vl5nOV7oHIJgJjz-WLgEzr396N56X2B39hlibGByP7U",
            "timestamp": "2019-11-01T22:07:58.582595Z",
            "public_key": ""
          },
          "last_modified": 1572646079396
        },
        "permissions": {
          "write": [
            "account:normandy_server"
          ]
        }
      },
      "user_id": "account:normandy_server",
      "record_id": "863",
      "collection_id": "normandy-recipes",
      "resource_name": "record",
      "id": "0f049564-d93f-4403-a2e8-99f63302bf97",
      "last_modified": 1572646079412
    }

```

**Comment by tdsmith** [comment] 2019-11-07 01:17
Fascinating!

We can also consult the `normandy.recipe_freshness` telemetry, which shows that no clients reported receiving revision 2788, and no change for recipe 857 was observed at 22:08: https://sql.telemetry.mozilla.org/queries/65895/source#167287

I think that makes this bug a lot less heart-stopping. Thanks for pulling the records, Mathieu!

I guess another hypothesis to examine is that receiving recipe 863 stopped Normandy from processing the pending change for recipe 857.

Normandy uptake telemetry events doesn't show any error spikes: https://sql.telemetry.mozilla.org/queries/65894/source#167285

**Comment by tdsmith** [comment] 2019-11-07 18:05
This looks like this was actually an artefact caused by looking at the timestamps when event pings were received, and not the timestamps where events happened. I'm now convinced there was never any problem. 😬

The data science team often prefers server timestamps to client-reported time values because we know that the servers's clocks are correct, but that was a mistake here.

If we look at the unenrollment events on November 1 according to the _client-reported unenrollment time_, we see a very sharp peak at about 21:09, lasting for only a couple of minutes: https://sql.telemetry.mozilla.org/queries/65922/source#167342

The difference from the earlier plot, which appeared to show an unenrollment event beginning at 21:09 and terminating abruptly at 22:08, is that it counted events according to the time that the ping announcing the event was _received at the server_.

The event telemetry announcing the unenrollment must have been queued locally for many clients. I conjecture that the event appeared to end at 22:08 either because a one-hour timer expired since the unenrollment event had first been accumulated, or else the new remote settings publication at 22:08 created a bunch of new events that triggered an event ping. Either way, this no longer suggests a Normandy or Remote Settings bug to me.

**Comment by mythmon** [comment] 2019-11-07 18:40
I added the events from Tim's previous comment to the timeline doc, and marked the previous, server-time-based events as obsolete. These events paint a much nicer picture, that matches very closely what we would have hoped the sequence of events to be.

The spike in Tim's graph also demonstrates very nicely the power of our modern push-based recipe deployment system. This is very cool, and perhaps something we could use to show how responsive Remote Settings can be.

The original analysis was very spooky, but it seems like it was mostly an unlucky coincidence. I'm going to close this out. If anyone has any more concerns or data that should be added to this issue, feel free to add it below or re-open this issue if appropriate.

Thanks for the work everyone.

**Closed by mythmon** 2019-11-07 18:40 UTC
Labels: P1 - High Priority
