### ISSUE TITLE
Multiple "Opt-Out" experiments with the same name/slug can be wrongly created

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/normandy#1746] opened 2019-02-19 13:36 UTC
**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have valid credentials in order to access the NORMANDY Delivery Console https://delivery-console.stage.mozaws.net/.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://delivery-console.stage.mozaws.net/ and click the "Recipes" card.
3. Click the "New Recipe" button and create a new "Opt-Out" experiment.
4. Save and approve the experiment.
5. Go back to the "Recipes" page and click the "New Recipe" button.
6. Create a new "Opt-Out" experiment using exactly the same data as in the experiment from step 3.
7. Save and approve the experiment.
8. Observe the behavior.

**[Expected result]:**
- An error saying that the experiment's name/slug is already used by another experiment is displayed.

**[Actual result]:**
- The second "Opt-Out" experiment is saved as well.

**[Notes]:**
- Also, both experiments can be published.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/53018806-fa72b300-345b-11e9-94d9-5b79076a2b55.gif)

**Comment by mythmon** [comment] 2019-02-19 18:21
Data validity issues are related to the Normandy API Server, not the Delivery Console UI. I've moved this issue to the appropriate repository.

**Comment by rehandalal** [comment] 2019-03-23 01:21
Duplicate of https://github.com/mozilla/normandy/issues/1791

**Closed by rehandalal** 2019-03-23 01:21 UTC
