### ISSUE TITLE
TaskCluster builds intermittently failing while cloning mozilla-central

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#757] opened 2017-05-12 03:38 UTC
Here's [an example](https://tools.taskcluster.net/task-group-inspector/#/SO1tViRoRNC6Nd3Ljl-8bQ/WgIIY0UeSt-TSJHwNZRDIw?_k=uvv1jr) (with progress bars removed):

```
~
Downloading mozilla-central...
real URL is https://hg.mozilla.org/mozilla-central/
destination directory: mozilla-central
applying clone bundle from https://s3-external-1.amazonaws.com/moz-hg-bundles-us-east-1/mozilla-central/d8762cb967423618ff0a488f14745f60964e5c49.packed1.hg
325316 files to transfer, 1.64 GB of data
transferred 1.64 GB in 61.0 seconds (27.4 MB/sec)
finished applying clone bundle
searching for changes
adding changesets
adding manifests
adding file changes                                                                                
added 252 changesets with 6009 changes to 3322 files
updating to branch default
abort: No such file or directory: '/root/mozilla-central/services/sync/tps/extensions'
abort: No such file or directory: '/root/mozilla-central/testing/web-platform/tests/html/semantics/common-idioms/rel-up'
abort: No such file or directory: '/root/mozilla-central/services/sync/tps/extensions/mozmill/resource/modules/stack.js'
```

**Comment by mythmon** [comment] 2017-05-12 17:19
We ran into this during our initial switch to mercurial as well, so it isn't a new thing.

```irc
<mythmon> while cloning, "abort: No such file or directory: '/root/mozilla-central/media/omx-plugin/include/ics'"
<rhelmer> during the clone?! that's really weird
```

**Comment by Osmose** [comment] 2017-05-23 19:35
@indygreg Could you help us figure out why we're seeing these cloning failures in TaskCluster? We're getting them when just running `hg clone http://hg.mozilla.org/mozilla-central/`, and we're using the same workers as the normal TC Firefox builds use.

**Comment by indygreg** [comment] 2017-05-23 20:46
That's a pretty special error. Fortunately, it rings a bell. I'm pretty certain the problem is an AUFS filesystem bug courtesy of TaskCluster running Docker. (By default / in TaskCluster is an AUFS volume.) For performance reasons (bug 1291940) and consistency reasons, you'll want to do as little work on AUFS as possible and instead use "cache" volumes, which are just EXT4 filesystems bind mounted into the Docker container.

The TaskCluster code in mozilla-central already does optimal things. Namely it sets up caches and scopes (see helper functions in https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/taskgraph/transforms/job/common.py) and run-task (https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/docker/recipes/run-task) for ensuring proper permissions and using `hg robustcheckout` to get a checkout as consistently and efficiently as possible. Every piece of complexity has been added for a reason and is necessary to guard various failure scenarios. Countless hours were spent making all this as robust as possible. Ideally you would just reuse it all verbatim. But since you are outside of mozilla-central, you'll have to copy some code and methods. This means you'll almost certainly drift behind on best practices and encounter bugs that have already been fixed by Firefox CI. The robustness of your CI will suffer.

I recommend changing the model of your CI to do version control magic to sync a Git[Hub] project into a sub-directory of mozilla-central then piggyback off Firefox's CI infrastructure. I am actively working on the VCS bits in bug 1357597.

**Comment by mythmon** [comment] 2017-06-02 23:47
The change in #788 (use robustcheckout) helped, but didn't entirely get rid of this problem. [Here is an example of a build](https://tools.taskcluster.net/task-group-inspector/#/ZVNjKTqJTQeiO8LEbeYcMg/bOkYrzSoTduCgjWKMm30bw?_k=6hw974) which, despite robustcheckout retrying, ran into enough problems that it still failed.

I think the next step here is to look into using a non-AUFS filesystem for the destination of the mercurial repo, like @indygreg suggested.

@indygreg thanks for the recommendations. I think that the change to our CI model you proposed would be a good thin in the long term. I've been watching this kind of work closely, and when it is ready I'd be happy to try it out.

**Comment by notriddle** [comment] 2017-12-15 21:02
Now that [Firefox isn't using AUFS](https://gregoryszorc.com/blog/2017/12/08/good-riddance-to-aufs/), does Normandy still use it? If so, what would it take to get on overlayfs?

**Comment by mythmon** [comment] 2017-12-18 20:50
@notriddle Normandy's CI doesn't do anything with filesystems, so we are likely still on AUFS. The problems AUFS pose come up for us rarely, so it hasn't been a high priority to fix. That post you linked to is talking about the Firefox build system, which is much larger than more complex that Normandy's (even though they share several properties).

In the near future, we're likely going to move the Normandy client's primary repository to mozilla-central. That would make this issue irrelevant, since we won't be running Task Cluster jobs anymore.

**Comment by indygreg** [comment] 2017-12-19 00:03
The change we made in Firefox's CI was universally made to all Docker workers in Mozilla's TaskCluster deployment. (The change was made at the AMI layer and all workers were updated to the latest AMI.) If Normandy's CI is using a worker defined at https://tools.taskcluster.net/aws-provisioner/, it is likely not using AUFS any more.

**Comment by mythmon** [comment] 2017-12-19 00:10
I stand corrected then! I also had my timelines wrong. I thought that your blog post happened well before the last time I saw this failure, but reviewing the timestamps more closely, it looks like we haven't seen this problem since before the AUFS changes were put in place.

I'll keep an eye on this for a little while longer, but if I don't see it again soon, I guess we can close this issue out.

Thanks for the help!

**Comment by mythmon** [comment] 2018-01-30 20:23
This hasn't happened in some time, and we're going to be moving the add-on into tree, so we won't have Taskcluster CI on this repo any more.

**Closed by mythmon** 2018-01-30 20:23 UTC
Labels: techdebt
