### ISSUE TITLE
Fix Jexl [] undefined issues

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#782] opened 2017-05-25 22:35 UTC
When Jexl gets a dotted path like `foo.bar.baz`, it safely cascades undefineds. (if `foo.bar` is undefined, `foo.bar.baz` will also return undefined, instead of erroring)

Jexl also supports bracketed access, like `foo.bar["baz"]`. In this case`["baz"]` is special case of a "filter expression" (no not that kind) that can return a subset of an object. For example `normandy.addons[.version > "1.0"]` would return a list of add-ons that have a version greater than 1.0. Additionally, if the resulting list has exactly one element, it returns a single object instead of a list.

Because of these filter expressions if `foo.bar` is undefined, `foo.bar["baz"]` throws an error, since there is nothing to filter. This is a problem because we have recipes that access things like `normandy.telemetry.main.addons["some addon id"].version`. If any of these keys are undefined, it errors out.

This issue covers fixing bracketed access to that it cascades undefined safely, like dotted access.

An open question: Should we try and preserve filter expressions while doing so?

**Comment by mythmon** [comment] 2017-05-25 22:38
My current thinking is that we are going to have to fork Jexl to accomplish this. The best name we've come up with for this is mozjexl (or some other capitalization).

**Comment by Osmose** [comment] 2017-05-25 22:42
Dupe of #767.

**Closed by Osmose** 2017-05-25 22:42 UTC
