### ISSUE TITLE
Create 'select' object for recipe action dropdown element

### ISSUE THREAD

**Issue by 18epedersen** [mozilla/normandy#932] opened 2017-07-27 18:10 UTC
I would greatly appreciate if you guys could make the recipe action dropdown menu a select object with values such as 'console-log', 'show-heartbeat', and 'preference-experiment' in order to make writing selenium tests easier. Just for reference, in the previous staging version, you guys used a select object for the action dropdown menu. Thanks!

**Comment by rehandalal** [comment] 2017-07-27 18:47
+1 to not building custom components unless absolutely necessary. That was the point of using Ant.

**Comment by andymikulski** [comment] 2017-07-27 18:55
@18epedersen Can you elaborate on your need for the `select`? Can the tests be written with what's in place? Better question: what _can't_ be tested with what's in place?

**Comment by 18epedersen** [comment] 2017-07-27 22:34
I would prefer the dropdown element to have a select id so I can use the Select object supported by Selenium. In Selenium, you can't make a webelement a Select object if it does not have a select id.

Here is an example from [stackoverflow ](https://stackoverflow.com/questions/12940592/how-to-select-an-item-from-a-dropdown-list-using-selenium-webdriver-with-java) of some HTML code and you can use Select to grab that select element and values from that select element:

Just wrap your WebElement into Select Object as shown below

Select dropdown = new Select(driver.findElement(By.id("identifier")));

Once this is done you can select the required value in 3 ways. Consider an HTML file like this

<html>
<body>
<select id = "designation">
<option value = "MD">MD</option>
<option value = "prog"> Programmer </option>
<option value = "CEO"> CEO </option>
</option>
</select>
<body>
</html>

Now to identify dropdown do

Select dropdown = new Select(driver.findElement(By.id("designation")));

To select its option say 'Programmer' you can do

dropdown.selectByVisibleText("Programmer ");

or

 dropdown.selectByIndex(1);

or

 dropdown.selectByValue("prog");

**Comment by Osmose** [comment] 2017-07-28 00:18
Seems like there are two feasible options:

1. Write a wrapper for Selenium that has a similar API as its built-in select stuff, but that actually ends up simulating clicks on the Ant non-select UI. I mildly think this is the better option. @18epedersen, would having to do this severely delay the rest of your work on these tests?

2. Write a component that wraps the Ant select component and injects a hidden select into the DOM that mirrors the Ant select. I think we might be able to just inject the props coming from the form into both elements and it'll "just work". We'd have to loop over the children passed in and convert them to standard DOM options, but that's probably not the worst?

   I'm only kinda guessing that that'd work though. We'd need to test it.

**Comment by andymikulski** [comment] 2017-07-28 15:52
>Write a component that wraps the Ant select component and injects a hidden select into the DOM that mirrors the Ant select.

I think the issue is that the Selenium tests aim to click on the select `option`s to alter the form values and go from there, so if we had our own secret select somewhere on the page, we'd have to fire changes in both directions.

@18epedersen Do you need to interact with the `select` (like fake clicks), or do you just need to read its values?

**Comment by Osmose** [comment] 2017-07-28 16:34
> I think the issue is that the Selenium tests aim to click on the select options to alter the form values and go from there, so if we had our own secret select somewhere on the page, we'd have to fire changes in both directions.

Yeah, but Ant just passes down an `onChange` prop and a `value` prop. My thought was that the wrapper would forward those props to both the Ant select and the native select, which would handle the back-and-forth sync between the two (since `value` will update when the value changes).

**Comment by rehandalal** [comment] 2017-07-28 16:53
> Write a wrapper for Selenium that has a similar API as its built-in select stuff, but that actually ends up simulating clicks on the Ant non-select UI. I mildly think this is the better option.

+1. 

I think it is weird to be writing components to match the tests rather than the other way around. We should only be building our own components if the included ones are broken or un-testable. I don't think either is the case here.

**Comment by 18epedersen** [comment] 2017-07-28 16:55
@andymikulski I need to interact with the select to make 'fake' clicks in order to select an action to make a recipe. With the current implementation, I can't make a selenium Select object of the dropdown menu because it does not have a select id, so i can't stimulate selecting an action which delays my tests.

**Comment by 18epedersen** [comment] 2017-07-28 22:29
@andymikulski  It's all good now! I'm able to select the action dropdown without you guys needing to add a select id. Thanks!

**Comment by mythmon** [comment] 2017-07-28 23:04
Closing per @18epedersen's comment.

**Closed by mythmon** 2017-07-28 23:04 UTC
